# Name the application the same as in your .platform.app.yaml.
name: tikatrial
# Use the recipe appropriate for your application.
recipe: drupal8

proxy:
  # Lets get a nice lndo url for the solr web interface
  solrindex:
    - solr.tikatrial.lndo.site:8983

# The following additional build step will install the Platform CLI
# in the application container.
services:
  appserver:
    extras:
      # Apache Tika
      - apt-get update -y
      - apt-get install -y openjdk-7-jre-headless
      - apt-get install -y openjdk-7-jdk
      - mkdir -p /srv/bin && cd /srv/bin
      - cd /srv/bin && curl -OL http://download.nextag.com/apache/tika/tika-app-1.16.jar
      - apt-get remove openjdk-7-jdk -y
    build:
      - "curl -sS https://platform.sh/cli/installer | php"

  # Spin up a solr container called "solrindex"
  solrindex:
    # Use solr version latest
    type: solr:6.5

# The following entry creates a `lando platform` command that will run
# any Platform CLI command from inside the container if desired.
tooling:
  platform:
    service: appserver
    description: Run Platform CLI commands
    cmd:
      - /var/www/.platformsh/bin/platform
    options:
      passthrough: true
  drush:
    service: appserver
    cmd:
      - "drush"
      - "--root=/app/web"

config:
  # Lando defaults to Apache. Switch to nginx to match Platform.sh.
  via: nginx

  # Set the webroot to match your .platform.app.yaml.
  webroot: web

  # Lando defaults to the latest MySQL release, but Platform.sh uses MariaDB.
  # Specify the version to match what's in services.yaml.
  database: mariadb:10.1
